Description: "This template shows how to create a VPC, Internet Gateway, to attach the Internet Gateway to VPC, to create subnets, to create a public Route Table and create a route in route table."

Parameters:
  VpcName:
    Description: VPC Name
    Type: String
    Default: myVPC1

  VpcCIDR:
    Description: IP Range (CIDR Notation) for VPC
    Type: String
    Default: 10.0.0.0/16

  # Creating 3 subnets (Each for different AZ)
  Subnet1CIDR:
    Description: Enter the IP Range (CIDR Notation) for the subnet in AZ 1
    Type: String
    Default: 10.0.1.0/24

  Subnet2CIDR:
    Description: Enter the IP Range (CIDR Notation) for the subnet in AZ 2
    Type: String
    Default: 10.0.2.0/24

  Subnet3CIDR:
    Description: Enter the IP Range (CIDR Notation) for the subnet in AZ 3
    Type: String
    Default: 10.0.3.0/24

Resources:
  # Create a VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: !Ref VpcName

  # Create an Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  # Attach the Internet Gateway to VPC
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Create a public route table for the VPC
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags: 
      - Key: Name
        Value: RouteTable

  # Add routes in the route table
  Route:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Create a subnet in AZ 1
  Subnet1:
    Type: AWS::EC2::Subnet
    DependsOn: VPC
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ''] # AZ 1
      CidrBlock: !Ref Subnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: Subnet1

  # Create a subnet in AZ 2
  Subnet2:
    Type: AWS::EC2::Subnet
    DependsOn: VPC
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ''] # AZ 2
      CidrBlock: !Ref Subnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: Subnet2

  # Create a subnet in AZ 3
  Subnet3:
    Type: AWS::EC2::Subnet
    DependsOn: VPC
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, !GetAZs ''] # AZ 3
      CidrBlock: !Ref Subnet3CIDR
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: Subnet3

  # Associate Route Table with subnet in AZ 1
  Subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet1

  # Associate Route Table with subnet in AZ 2
  Subnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet2

  # Associate Route Table with subnet in AZ 3
  Subnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet3